--1
SELECT 
    C.NOME AS NomeCliente,
    P.PAGAMENTO AS MeioPagamento
FROM 
    FINANCIAMENTOS F
JOIN 
    CLIENTES C ON F.IDCLIENTE = C.IDCLIENTE
JOIN 
    TIPOPAGAMENTO P ON F.IDPAGAMENTOS = P.IDPAGAMENTOS;
	
--2
SELECT 
    C.NOME AS NomeCliente,
    B.BEMFINANCIADO AS BemFinanciado
FROM 
    FINANCIAMENTOS F
JOIN 
    CLIENTES C ON F.IDCLIENTE = C.IDCLIENTE
JOIN 
    TIPOBEMFINANCIADO B ON F.IDBEMFINANCIADO = B.IDBEMFINANCIADO;

	
--3
SELECT 
    C.ESTADOCIVIL,
    B.BEMFINANCIADO,
    SUM(F.VALORCREDITO) AS TotalFinanciado
FROM 
    FINANCIAMENTOS F
JOIN 
    CLIENTES C ON F.IDCLIENTE = C.IDCLIENTE
JOIN 
    TIPOBEMFINANCIADO B ON F.IDBEMFINANCIADO = B.IDBEMFINANCIADO
GROUP BY 
    C.ESTADOCIVIL, B.BEMFINANCIADO;
	
--4
SELECT 
    AVG(D.DURACAOMESES) AS DuracaoMediaMeses
FROM 
    FINANCIAMENTOS F
JOIN 
    CLIENTES C ON F.IDCLIENTE = C.IDCLIENTE
JOIN 
    DURACAO D ON F.IDDURACAO = D.IDDURACAO
WHERE 
    C.IDADE BETWEEN 30 AND 40;

--5
SELECT 
    C.NOME AS NomeCliente,
    TC.TIPOCONTRATO AS TipoContrato
FROM 
    FINANCIAMENTOS F
JOIN 
    CLIENTES C ON F.IDCLIENTE = C.IDCLIENTE
JOIN 
    TIPOCONTRATO TC ON F.IDTIPOCONTRATO = TC.IDTIPOCONTRATO
WHERE 
    C.IDCLIENTE = 5;
	
--6
SELECT 
    C.NUMEROFILHOS,
    D.DURACAOMESES
FROM 
    FINANCIAMENTOS F
JOIN 
    CLIENTES C ON F.IDCLIENTE = C.IDCLIENTE
JOIN 
    DURACAO D ON F.IDDURACAO = D.IDDURACAO
ORDER BY 
    C.NUMEROFILHOS;
	

--7
SELECT 
    C.NOME AS NomeCliente,
    TS.TIPO_SITUACAO AS SituacaoCliente
FROM 
    FINANCIAMENTOS F
JOIN 
    CLIENTES C ON F.IDCLIENTE = C.IDCLIENTE
JOIN 
    TIPOSITUACAO TS ON F.IDSITUACAO = TS.IDSITUACAO;


