insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (1, 'Educação Física Escolar', 2, 36, 8, 'Townsend Beamish');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (2, 'Nutrição e Dietética', 3, 27, 10, 'Adriana Meconi');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (3, 'Nutrição e Dietética', 6, 57, 3, 'Felike Northill');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (4, 'Sistemas de Informação em Gestão', 6, 33, 7, 'Farrel Solan');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (5, 'História da Literatura Portuguesa', 2, 22, 8, 'Valma Wherrit');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (6, 'Teoria da Literatura', 4, 41, 2, 'Cathie Blouet');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (7, 'Gestão de Operações', 2, 25, 8, 'Sofie Weond');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (8, 'Gestão de Empresas', 2, 54, 2, 'Kayley Wormell');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (9, 'Análise de Investimentos', 4, 28, 3, 'Trixy Molohan');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (10, 'Nutrição e Dietética', 5, 21, 7, 'Marguerite Norres');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (11, 'Cuidados Paliativos', 2, 44, 3, 'Marje Balnave');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (12, 'Liderança e Gestão de Equipas', 5, 52, 7, 'Nikaniki Gotliffe');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (13, 'Metodologia do Treino de Força', 3, 60, 3, 'Emilia Tissier');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (14, 'Big Data', 1, 35, 9, 'Verge Downer');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (15, 'Logística e Cadeia de Suprimentos', 2, 46, 6, 'Filia Vinson');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (16, 'Reabilitação Desportiva', 2, 46, 5, 'Bel Carruth');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (17, 'Big Data', 2, 34, 7, 'Ethelred Goley');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (18, 'Sociologia do Desporto', 3, 25, 5, 'Tommie Mathey');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (19, 'Ética no Desporto', 5, 31, 8, 'Brent Lehr');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (20, 'Gestão de Risco', 3, 33, 4, 'Perceval O''Dennehy');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (21, 'Estilística', 6, 22, 5, 'Stuart Doubrava');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (22, 'Gestão de Empresas', 4, 44, 2, 'Anica D''Ambrogio');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (23, 'Saúde Pública', 4, 45, 9, 'Phelia Sandry');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (24, 'Logística e Cadeia de Suprimentos', 2, 57, 4, 'Elisa Gartery');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (25, 'Planeamento Estratégico', 4, 55, 10, 'Shawn Hatto');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (26, 'Saúde Pública', 3, 51, 3, 'Cally Sheavills');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (27, 'Fisiologia do Exercício', 2, 34, 7, 'Fulvia Harcombe');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (28, 'Tradução e Interpretação', 1, 53, 5, 'Burnaby Kilrow');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (29, 'Redes de Computadores', 6, 22, 8, 'Rogerio Garratt');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (30, 'Estudos de Género', 6, 48, 9, 'Tory Danne');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (31, 'Inteligência Artificial', 6, 43, 2, 'Lock Dounbare');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (32, 'Edição e Revisão de Textos', 5, 30, 6, 'Natalya Geistbeck');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (33, 'Imagiologia Médica', 4, 57, 2, 'Callie Busek');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (34, 'Literatura Contemporânea', 4, 24, 3, 'Andree Eshelby');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (35, 'Gestão de Projetos', 2, 43, 2, 'Kimmy Seak');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (36, 'Reabilitação Desportiva', 2, 39, 5, 'Eimile Spada');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (37, 'Retórica e Argumentação', 4, 41, 6, 'Edee Rodenborch');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (38, 'Psicologia da Saúde', 5, 22, 3, 'Fred Andino');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (39, 'Computação Gráfica', 3, 36, 8, 'Jacquenette Cuerda');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (40, 'Retórica e Argumentação', 2, 51, 4, 'Bride Parish');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (41, 'Reabilitação Física', 4, 60, 3, 'Siward Trundell');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (42, 'Gestão Desportiva', 4, 33, 8, 'Yvon Ivatts');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (43, 'Anatomia Humana', 1, 58, 3, 'Avery Kohnemann');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (44, 'Gestão Desportiva', 6, 27, 7, 'Briggs Cliss');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (45, 'Cibersegurança', 1, 56, 7, 'Peggi Alltimes');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (46, 'Negócios Internacionais', 4, 41, 2, 'Lishe Stearns');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (47, 'Sistemas de Informação em Gestão', 2, 55, 7, 'Carr Royall');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (48, 'Negócios Internacionais', 1, 37, 8, 'Patten Lamburn');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (49, 'Nutrição no Desporto', 6, 40, 6, 'Wells Bartlett');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (50, 'Fonética e Fonologia', 2, 22, 7, 'Lonni Bagniuk');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (51, 'IoT (Internet of Things)', 6, 54, 8, 'Zebadiah Irce');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (52, 'Microbiologia', 3, 54, 8, 'Alisander Fass');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (53, 'Edição e Revisão de Textos', 4, 40, 4, 'Kaja Seary');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (54, 'Liderança e Gestão de Equipas', 6, 30, 4, 'Karee Thorne');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (55, 'Sociologia do Desporto', 1, 39, 8, 'Ingunna Cunnow');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (56, 'Literatura Infantojuvenil', 1, 52, 9, 'Aubry Addyman');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (57, 'Anatomia do Movimento', 4, 31, 5, 'Adela Roobottom');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (58, 'Ética e Responsabilidade Social', 3, 41, 10, 'Konrad Bigley');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (59, 'Computação Gráfica', 2, 43, 4, 'Elsinore Lehrian');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (60, 'Bioquímica', 4, 26, 5, 'Doll Kingzet');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (61, 'Ética e Responsabilidade Social', 6, 26, 4, 'Cordie Cello');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (62, 'Segurança Informática', 5, 54, 9, 'Marysa Leftly');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (63, 'Imagiologia Médica', 1, 53, 8, 'Wilone Gierhard');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (64, 'Farmacologia', 4, 25, 7, 'Jareb Laslett');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (65, 'História da Língua Portuguesa', 2, 56, 5, 'Karlotta Smalecombe');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (66, 'Big Data', 6, 34, 3, 'Bruno Reynoldson');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (67, 'Psicologia do Desporto', 3, 22, 6, 'Anabel Bannard');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (68, 'Gestão Desportiva', 5, 54, 8, 'Bess Firsby');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (69, 'Marketing Estratégico', 4, 53, 9, 'Thadeus Cumpton');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (70, 'Anatomia do Movimento', 2, 58, 10, 'Richie Gomby');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (71, 'Psicologia da Saúde', 2, 47, 6, 'Josee Goodlett');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (72, 'Liderança e Gestão de Equipas', 1, 42, 10, 'Priscella Ormes');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (73, 'Cuidados Paliativos', 3, 33, 5, 'Cecelia Permain');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (74, 'Gestão Desportiva', 4, 58, 8, 'Flora Toothill');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (75, 'Edição e Revisão de Textos', 3, 56, 2, 'Shelia Kenaway');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (76, 'Retórica e Argumentação', 5, 21, 7, 'Bidget Fradgley');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (77, 'Educação para a Saúde', 4, 47, 2, 'Cal Stopps');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (78, 'Big Data', 1, 21, 8, 'Harriette Meaddowcroft');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (79, 'Bioquímica', 6, 42, 8, 'Elliot Robeiro');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (80, 'Avaliação e Prescrição de Exercício', 3, 34, 4, 'Korey Whoolehan');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (81, 'História da Língua Portuguesa', 1, 44, 10, 'Alikee Northcote');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (82, 'Computação Gráfica', 5, 56, 3, 'Faunie Klammt');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (83, 'Patologia Geral', 4, 33, 7, 'Daniella Redit');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (84, 'Gestão Hospitalar', 4, 56, 9, 'Ewen Bourner');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (85, 'Sistemas Operativos', 6, 21, 6, 'Axe Scrammage');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (86, 'Edição e Revisão de Textos', 5, 60, 4, 'Gilbertina Semple');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (87, 'Enfermagem Clínica', 5, 35, 5, 'Alessandra Baverstock');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (88, 'Educação para a Saúde', 5, 51, 5, 'Clarine Suddaby');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (89, 'Liderança e Gestão de Equipas', 6, 34, 2, 'Berta Shepton');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (90, 'Estatística no Desporto', 2, 56, 6, 'Raffarty Bicksteth');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (91, 'Robótica', 2, 22, 2, 'Sky Justham');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (92, 'Cuidados Paliativos', 2, 37, 7, 'Arly Viggars');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (93, 'Gestão de Risco', 6, 35, 3, 'Rustin Edyson');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (94, 'Introdução à Linguística', 2, 49, 8, 'Galven Havelin');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (95, 'Retórica e Argumentação', 6, 44, 2, 'Ania Danneil');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (96, 'Pedagogia do Desporto', 4, 59, 8, 'Scotti Napolione');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (97, 'Gestão de Projetos de TI', 3, 38, 7, 'North Leonardi');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (98, 'Negócios Internacionais', 1, 40, 7, 'Wait Straneo');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (99, 'Gestão de Operações', 6, 46, 5, 'Herbie Beevors');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (100, 'Planeamento Estratégico', 3, 30, 2, 'Pascale Kenningham');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (101, 'Avaliação e Prescrição de Exercício', 1, 38, 6, 'Emmott Conneely');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (102, 'Cibersegurança', 4, 34, 10, 'Prisca Seggie');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (103, 'Reabilitação Desportiva', 2, 32, 5, 'Leonhard Loude');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (104, 'Teoria da Literatura', 5, 22, 4, 'Ethelda Tewkesbury');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (105, 'Gestão de Operações', 2, 60, 10, 'Engracia Ledbetter');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (106, 'Comportamento Organizacional', 6, 28, 2, 'Anni Chawkley');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (107, 'Patologia Geral', 3, 22, 3, 'Ruby Meadowcraft');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (108, 'Fisiologia Geral', 5, 57, 6, 'Barnaby Rowbury');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (109, 'Gestão de Risco', 5, 39, 8, 'Krissie MacKonochie');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (110, 'Estilística', 1, 54, 2, 'Natalie Becerra');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (111, 'Análise de Investimentos', 1, 48, 4, 'Dorey Busby');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (112, 'Teoria do Treino Desportivo', 1, 57, 9, 'Anson Kleuer');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (113, 'Saúde Mental', 6, 53, 6, 'Trudi Keeler');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (114, 'Ética e Deontologia em Saúde', 6, 51, 6, 'Kylynn Verma');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (115, 'Edição e Revisão de Textos', 5, 51, 9, 'Flory Scintsbury');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (116, 'Negócios Internacionais', 3, 33, 8, 'Iain Painswick');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (117, 'Nutrição no Desporto', 4, 39, 6, 'Haywood Fish');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (118, 'Sistemas Operativos', 6, 52, 5, 'Pam Clues');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (119, 'Sistemas Operativos', 5, 35, 5, 'Corinne Willimott');
insert into disciplinas (id_disciplina, nome_disciplina, semestre, carga_horaria, ects, responsavel) values (120, 'Treino Funcional', 5, 31, 10, 'Kalil Findon');
